eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/fanjia12/config-repo
          username: 851537449@qq.com
          password: fanjia521